INSERT INTO subjects(code, name) VALUES('112', 'ENGLISH'),('456', 'MATHEMATICS'),
('545', 'CHEMISTRY'),
('553', 'BIOLOGY'),
('535', 'PHYSICS'),
('527', 'AGRICULTURE'),
('241', 'HISTORY'),
('273', 'GEOGRAPHY'),
('224', 'C.R.E'),
('225', 'I.R.E'),
('335', 'LUGANDA'),
('845', 'ENTREPRENEURSHIP'),
('840', 'I.C.T'),
('208', 'LITERATURE'),
('610', 'FINE ART')

('$student_no', 'ENGLISH'),
('$student_no', 'MATHEMATICS'),
('$student_no', 'CHEMISTRY'),
('$student_no', 'BIOLOGY'),
('$student_no', 'PHYSICS'),
('$student_no', 'AGRICULTURE'),
('$student_no', 'HISTORY'),
('$student_no', 'GEOGRAPHY'),
('$student_no', 'C.R.E'),
('$student_no', 'I.R.E'),
('$student_no', 'LUGANDA'),
('$student_no', 'ENTREPRENEURSHIP'),
('$student_no', 'I.C.T'),
('$student_no', 'LITERATURE'),
('$student_no', 'FINE ART')


